apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraudgraphx-ingress
  namespace: fraudgraphx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fraudgraphx.example.com
      secretName: fraudgraphx-tls
  rules:
    - host: fraudgraphx.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: fraudgraphx-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fraudgraphx-frontend
                port:
                  number: 80
